version: '3.8'

services:
  app:
    build: .
    container_name: shortener
    ports:
      - "8080:8080"
    depends_on:
      - postgres-shortener
      - redis-shortener
    environment:
      POSTGRES_ADDR: ${POSTGRES_ADDR}
      REDIS_ADDR: ${REDIS_ADDR}

  postgres-shortener:
    image: postgres:15
    container_name: postgres-shortener
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis-shortener:
    image: redis:latest
    container_name: redis-shortener
    ports:
      - "6379:6379"

volumes:
  pgdata:
